project_id = "rxoykogmyitwmdqxytvd"

[functions.fb-conversion]
verify_jwt = false

[functions.analytics-auth]
verify_jwt = false

[functions.get-medicare-quote]
verify_jwt = false

[functions.send-lead-webhook]
verify_jwt = false

[functions.send-lead-webhook-suppappt]
verify_jwt = false

[functions.schedule-callback]
verify_jwt = false

[functions.validate-contact]
verify_jwt = false

[functions.ghl-calendar]
verify_jwt = false
